### ISSUE TITLE
Unfortunately crashing :(

### ISSUE THREAD

**Issue by VladisCrafter** [ferriarnus/ReForgedPlay#1]
https://mclo.gs/h2vuQY6

`Minecraft 1.20.1, Forge 47.2.17`
No other mods are present, all disabled.

**Comment by ferriarnus** [comment]
I have yet to test 1.18 - 1.19.2 in prod (as they do work in my ide). I'll look into it soon-ish, shouldn't be too bad to figure out.

**Comment by ferriarnus** [comment]
Should be fixed now, that was more painful then I thought it would be
