### ISSUE TITLE
Failed apply mixin for 1.20.1 latest version

### ISSUE THREAD

**Issue by Igneo220** [ferriarnus/ReForgedPlay#14]
the latest build crashes the game and fails to apply a mixin. The version directly previous, however, does not have this issue

[latest.log](https://github.com/user-attachments/files/16631390/latest.log)

The launcher insists this is a ram issue. This is a heavily modded instance as well

**Comment by ferriarnus** [comment]
This makes no sense, since this mixin is present on the previous version as well. Did you change anything else?

**Comment by kakashi1464** [comment]
[latest.log](https://github.com/user-attachments/files/16641022/latest.log)
same for me on the clean instance, nothing was modified in the mod itself

**Comment by ferriarnus** [comment]
Dammit, did the arch remap thing break again? I'll check it out again and reupload it.

**Comment by Reignofmagic** [comment]
I can confirm that the crash happens as well with only the replay mod installed.

**Comment by ferriarnus** [comment]
Yep, found the issue, a new release will be out later today fixing it
