### ISSUE TITLE
doesn’t work yet with the new versions of sodium and iris on 1.21.1

### ISSUE THREAD

**Issue by TheVirusNVGM** [ferriarnus/ReForgedPlay#18]
https://paste.atlauncher.com/view/3c47e1a3-f221-4bb9-8cfc-a83b24084d4f

Unfortunately, when a crash occurs, no crash log appears, so get only regular logs

**Comment by ferriarnus** [comment]
Correct, use embeddium instead of sodium for now (but no shaders for now)
