### ISSUE TITLE
Feet movement not recorded

### ISSUE THREAD

**Issue by Katz204** [ferriarnus/ReForgedPlay#21]
While crouching is recorded, it seems like my character just glided and not having any leg movement

**Comment by Loaferrrrrr** [comment]
Bit late to the forum but if you still want to use not enough animations turn **off** Animation Smoothing and turn **on** Disable Leg Smoothing. Then everything else should still work. :)

![Image](https://github.com/user-attachments/assets/45f59fbd-d295-49f5-ba4f-1b8f884e5c3c)
