### ISSUE TITLE
FREX flawless frames API, how ironic

### ISSUE THREAD

**Issue by VladisCrafter** [ferriarnus/ReForgedPlay#3]
Well, it could've been ideal if not... you probably know that one.
![image](https://github.com/ferriarnus/ReForgedPlay/assets/122053125/1bd3bca1-498c-4b2b-bced-6a617fb0f52e)
`Embeddium 0.3.19`

**Comment by ferriarnus** [comment]
I'll have a look later

**Comment by ferriarnus** [comment]
might be related to https://github.com/Sinytra/Connector/issues/932#issuecomment-2103065315?

**Comment by ferriarnus** [comment]
Ok, issue has been found, and I'll look into a propper fix. If nothing happens soon-ish (when I'm back at my pc), I'll simply remove the message and let it be rendered.

**Comment by kakashi1464** [comment]
could this solve the issue?
https://github.com/embeddedt/embeddium/commit/afe39fe39414e5772bec94cd3050b0b9840f2f23

**Comment by ferriarnus** [comment]
Yep  asked embeddedt if he could provide something like that. I'll have a look at actually using it now.
