### ISSUE TITLE
Github Actions fix?

### ISSUE THREAD

**Issue by kakashi1464** [ferriarnus/ReForgedPlay#4]
![image](https://github.com/ferriarnus/ReForgedPlay/assets/126709049/96ac262b-39f0-4d8c-8b3f-4bf917b72fe7)
It would be nice if people could download the mod via github actions

**Comment by VladisCrafter** [comment]
Affirmative

**Comment by ferriarnus** [comment]
I'll look around if I still have a github action script laying around, shouldn't be too bad to make.
