### ISSUE TITLE
Change key binding support

### ISSUE THREAD

**Issue by PTALTS-LK** [ferriarnus/ReForgedPlay#5]
The M key conflicts with various minimap mods, is it possible to add a way to change the key bindings?

**Comment by VladisCrafter** [comment]
Most probably this won't be changed. ReForgedPlay is made just to bring Replay mod to Forge and Neo. The author is probably not going to change any original stuff except for technical if it's necessary.

**Comment by ignotus-glitch** [comment]
I think he meant adding ability to change key binds by players in `Options/Controls/Key Binds`, because there is non from this mod.

**Comment by VladisCrafter** [comment]
strange, this should exist as in the official Replay mod, shouldn't it?..

**Comment by ignotus-glitch** [comment]
Yes, it should

**Comment by ferriarnus** [comment]
I'll check this when I have time, but I thought I did add it? What mc version?

**Comment by ferriarnus** [comment]
Found the issue, I'll try to make a release this week

**Comment by ignotus-glitch** [comment]
> I'll check this when I have time, but I thought I did add it? What mc version?

1.2

**Comment by ferriarnus** [comment]
resolved
