### ISSUE TITLE
Minecraft crashes 1.20.1

### ISSUE THREAD

**Issue by KristianCAA** [ferriarnus/ReForgedPlay#7]
while downloading mods, minecraft crashes, I have installed: architectury-9.2.14, neoforge-1.20.1-4.3, moonlight-1.20-2.11.41, quilt-0.9.2, OptiFine-1.20.1_HD_U_I6_pre6

**Comment by VladisCrafter** [comment]
OptiFine? **Quilt?!** 💀

**Comment by ferriarnus** [comment]
I would need a log. And I don't recomment using optifine.

**Comment by ferriarnus** [comment]
no more info provided
